apiVersion: v1
kind: Service
metadata:
  name: {{ template "mock-ams-kong.fullname" . }}
  labels:
    app: {{ template "mock-ams-kong.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "mock-ams-kong.name" . }}
    release: {{ .Release.Name }}
