---
- hosts: api-service-server
  become: true

  tasks:
  - name: Copy Api Service Files
    copy:
      src: ../api/
      dest: /opt/dicky/kong-service/
      owner: root
      group: root
      mode: 0700
