---
- hosts: api-service-server
  become: true

  tasks:
  - name: Copy Api Service Files
    copy:
      src: ../api/
      dest: /opt/dicky/kong-service/
      owner: root
      group: root
      mode: 0640

  - name: CD into project directory
    raw: cd /opt/dicky/kong-service/api/

  - name: Install Packages
    raw: npm i

  - name: Start API
    raw: nohup npm start &