---
- hosts: api-service-server
  become: true

  tasks:
  - name: Copy Api Service Files
    copy:
      src: ../api/
      dest: /opt/dicky/kong-service/
      owner: root
      group: root
      mode: 0640

  - name: Install Packages
    raw: cd /opt/dicky/kong-service && npm i

  - name: Start Api
    raw: cd /opt/dicky/kong-service && nohup npm start &