---
- hosts: api-service-server
  become: true

  tasks:
  - name: Copy Api Service Files
    copy:
      src: ../api/
      dest: /opt/dicky/kong-service/
      owner: root
      group: root
      mode: 0640

  - name: Install Packages
    npm:
      executable: /usr/bin/npm --unsafe-perm=true --allow-root
      path: /opt/dicky/kong-service/api

  - name: Start Api
    raw: cd /opt/dicky/kong-service && nohup ./node_modules/pm2/bin/pm2-runtime process.yml --only local &